### PR TITLE
Updates to guides. Refactoring of existing code. Minor testing tweaks.

### PR DESCRIPTION
**Pull request by ghost**
This pull request address the following:
* Updates to Personal Portfolio page.
* Updates to User Guide (Quick Start, Tab, Clear).
* Updates to Developer Guide (UI, Import Command, auxiliary classes).
* Minor refactoring (Cleaning up unused methods, adding author tags and comments).
* Remove Navbar header from webpage. See #42 .

### CODE REVIEW

**Comment by itszp** [comment]
Thanks for updating your diagrams for standardisation. 
However, include the figure tags for your diagram as well.

**Review by itszp — CHANGES_REQUESTED** [review]
Thanks for updating your diagrams for standardisation. 
However, please include the tag for your diagrams as well.

**Review by kayheen — COMMENTED** [review]
In DG:
Line 200: The `UI` component is supported to a `Notifier` class. --> change 'to' to 'by'.

In UG: 
The alternatives, can explain why you choose that particular alternative.

**Comment by itszp** [comment]
Please remember to include the "Figure XX" tag for your diagrams.

**Comment by ghost** [comment]
> Please remember to include the "Figure XX" tag for your diagrams.

I added the captions for the diagrams as requested.

> In DG:
> Line 200: The `UI` component is supported to a `Notifier` class. --> change 'to' to 'by'.
> 
> In UG:
> The alternatives, can explain why you choose that particular alternative.

I don't see alternative options in UG can you point the line?

**Comment by itszp** [comment]
Great! Will merge once checks have passed.

**Review by itszp — APPROVED** [review]

**Comment by ghost** [comment]
> Great! Will merge once checks have passed.

Can go sleep.

**Comment by itszp** [comment]
> > Great! Will merge once checks have passed.
> 
> Can go sleep.

Sleep w ur mum

**Comment by kayheen** [comment]
> > In UG:
> > The alternatives, can explain why you choose that particular alternative.
> 
> I don't see alternative options in UG can you point the line?

Sorry I meant the DG @Carrein

**Pull request merged**
